name: datagrid_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  syncfusion_flutter_datagrid: ^23.1.36
  intl: ^0.18.1
  syncfusion_flutter_core: ^23.1.36
  syncfusion_flutter_charts: ^23.1.36
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

